modified github-actions

diff --git a/.github/workflows/construct-maven-develop.yml b/.github/workflows/construct-maven-develop.yml
--- a/.github/workflows/construct-maven-develop.yml
+++ b/.github/workflows/construct-maven-develop.yml
@@ -1,6 +1,9 @@
 name: Build and Test
 
 on:
+  pull_request:
+    branches:
+      - '*'
   push:
     branches:
       - '*'
@@ -23,3 +26,9 @@ jobs:
 
       - name: Build and Install
         run: mvn clean install
+
+      - name: Add label on failure
+        if: ${{ failure() }}
+        run: |
+          echo "::add-labels::failed-check"
+          echo "Failed checks. Do not merge." >&2
